algoritmo "semnome"
// Função :
// Autor :
// Data : 12/05/2020
// Seção de Declarações 
var
a,b,so,su,mu,di:real
inicio
// Seção de Comandos
a<-10
b<-5
escreval("programa das 4 operaçoes")
escreval("o valor de A é:",a)
escreval("o valor de B é:",b)
so<-a+b
su<-a-b
mu<-a*b
di<-a/b
escreval("A subtração de A e b é:" ,su)
escreval("A soma de A e b é:" ,so)
escreval("A multiplicação de A e b é:" ,mu)
escreval("A divisão de A e b é:" ,di)
fimalgoritmo
